<footer class="clearfix">
      <div class="footer-links">
        <div id="socials">
          <a href="javascript:void(0);" id="social-1" title="Connect with us on Facebook">Facebook</a>
          <a href="javascript:void(0);" id="social-2" title="Connect with us on Twitter">Twitter</a>
          <a href="javascript:void(0);" id="social-3" title="Connect with us on Instagram">Instagram</a>
          <a href="javascript:void(0);" id="social-4" title="Connect with us on Pinterest">Pinterest</a>
        </div>
        <nav id="sub-nav">
          <ul class="list-unstyled">
            <li><a href="<?php print url('brand');?>">Our Brands</a></li>
            <li><a href="<?php print url('contact-us');?>">Contact Us</a></li>
            <li><a href="<?php print url('tc');?>">Terms &amp; Conditions</a></li>
          </ul>
        </nav>
      </div>
      <div class="copyright">
        <div class="footer-logo"><img src="<?php print base_path().path_to_theme();?>/images/logo-footer.jpg" alt=""></div>
        <div class="cp-text">
          <p>Copyright 2015 <sup>&copy;</sup> Nestlé Products Snd Bhd (45229-H).</p>
          <p>All Right Reserved</p>
        </div>
      </div>
      <a id="btn-backtop" href="javascript:void(0);"></a>
    </footer>

    <!-- Welcome Modal -->
    <div class="modal fade" id="welcomeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
        <div class="modal-body">
          <div class="contain">
            <div class="row">
              <div class="col-sm-12">
                <div class="img-wrapper">
                  <img src="<?php print base_path().path_to_theme();?>/images/modal/welcome-modal-img.png"/>
                </div>
                <div class="txt-wrapper">
                  <h1 class="title">Welcome to Dear Nestle</h1>
                  <p class="desc">For mothers on the go, this website is packed with information and tips on healthy family living. Enjoy recipes, suggested workouts and advice on family bonding and leisure activities. </p>
                  <p class="desc">We’ve also put together a selection of articles as well as challenges to keep you motivated.  Earn points along the way to keep track of your progress and to redeem products from participating merchants, soon!</p>
                </div>
                <div class="modal-action">
                  <div class="btn-wrapper">
                    <a class="login-btn btn btn-green" href="javascript:void(0);">Log In</a>
                    <a class="signup-btn btn btn-green" href="javascript:void(0);">Sign Up</a>
                  </div>
                  <a class="later-btn" href="javascript:void(0);">Later</a>
                </div>
              </div>
            </div>
          </div>
        </div>

        </div>
      </div>
    </div>

    <!-- Delete private Recipe Modal -->
    <div class="modal fade" id="deleteRecipeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
        <div class="modal-body">
          <div class="contain">
            <div class="row">
              <div class="col-sm-12">

                <div class="txt-wrapper">
                  <p class="quest desc underline">Delete this recipe?</p>
                  <h1 class="title">Baked Lemon Honey Yogurt Chicken Drumettes</h1>
                  <p class="note desc"><strong>Please note: </strong>Once you delete this recipe, you can’t get it back later.</p>
                </div>
                <div class="modal-action">
                  <div class="btn-wrapper">
                    <a class="cancel-btn btn btn-green" href="javascript:void(0);">Cancel</a>
                    <a class="save-btn btn btn-green" href="javascript:void(0);">Save</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        </div>
      </div>
    </div>

    <!-- Forgot Password Modal -->
    <div class="modal fade" id="forgotPassModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
        <div class="modal-body">
          <div class="contain">
            <div class="row">
              <div class="col-sm-12">
                <div class="txt-wrapper">
                  <p class="title underline">Forgot Password</p>
                  <p class="desc">
                    An email has been sent to <a href="javascript:void(0);">amanda.wong@gmail.com</a> with password reset instructions. Please click on the link in the email to reset your password.
                  </p>
                </div>
                <div class="modal-action">
                  <div class="btn-wrapper">
                    <a class="return-login-btn btn btn-green" href="javascript:void(0);">Return to log in page</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        </div>
      </div>
    </div>

    <!-- Website Tour Modal -->
    <div class="modal fade" id="webTourModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
        <div class="modal-body">
          <div class="contain">
            <div class="row">
              <div class="col-sm-12">
                <div class="txt-wrapper">
                  <p class="title underline">Website Tour</p>
                  <p class="desc">
                    Check out the cool features on this website. Take a quick look by clicking on the website tour below.
                  </p>
                </div>
                <div class="modal-action">
                  <div class="btn-wrapper">
                    <a class="yes btn btn-green" href="javascript:void(0);">Yes, walk me through the tour</a>
                    <a class="no btn btn-green" href="javascript:void(0);">No, thanks</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        </div>
      </div>
    </div>

    <!-- Delete Photo Modal -->
    <div class="modal fade" id="deletePhotoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
        <div class="modal-body">
          <div class="contain">
            <div class="row">
              <div class="col-sm-12">
                <div class="txt-wrapper">
                  <p class="title underline">Delete this photo</p>
                  <div class="img-wrapper">
                    <img src="<?php print base_path().path_to_theme();?>/images/dummy/list1.jpg"/>
                  </div>
                </div>
                <div class="modal-action">
                  <div class="btn-wrapper">
                    <a class="cancel-btn btn btn-green" href="javascript:void(0);">Cancel</a>
                    <a class="delete-btn btn btn-green" href="javascript:void(0);">Delete</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        </div>
      </div>
    </div>

    <!-- Edit Photo Modal -->
    <div class="modal fade" id="editPhotoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
        <div class="modal-body">
          <div class="contain">
            <div class="row">
              <div class="col-sm-12">
                <div class="txt-wrapper">
                  <p class="title underline">Before you save this photo</p>
                  <p class="desc">To resize or crop your image, drag the zoom tool below to the left or right. Or drag your image to reposition it.
                  </p>
                  <div class="img-wrapper">
                    <img id="cropimage" alt="" src="<?php print base_path().path_to_theme();?>/images/dummy/03917_wdc56upclose_1366x768.jpg" />
                    <div class="slider-wrapper">
                      <a class="zoom-out" href="javascript:void(0);">
                        <img src="<?php print base_path().path_to_theme();?>/images/global/zoom-out.png" />
                      </a>
                      <div id="slider">
                      </div>
                      <a class="zoom-in" href="javascript:void(0);">
                        <img src="<?php print base_path().path_to_theme();?>/images/global/zoom-in.png" />
                      </a>
                    </div>
                  </div>

                </div>
                <div class="modal-action">
                  <div class="btn-wrapper">
                    <a class="cancel-btn btn btn-green" href="javascript:void(0);">Cancel</a>
                    <a class="save-btn btn btn-green" href="javascript:void(0);">Save Photo</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        </div>
      </div>
    </div>
