<div id="footer">
  <footer class="row">
    <div class="large-12 columns">
      <div class="row">
        <div class="large-4 columns">
          <p>Bản quyền &copy; 2015 - Nghệ Thuật Chữ Viết</p>
        </div>
        <div class="large-8 columns">
          <?php print theme('links__system_main_menu', array('links' => $secondary_menu, 'attributes' => array('id' => 'footer-menu', 'class' => array('inline-list','right')), 'heading' => '')); ?>
        </div>
      </div>
    </div>
  </footer>
</div>
